#|
Guile bindings to the libfive CAD kernel

DO NOT EDIT BY HAND!
This file is automatically generated from libfive/stdlib/stdlib.h

It was last generated on 2021-02-27 10:05:15 by user mkeeter
|#

(define-module (libfive stdlib text))
(use-modules (system foreign) (libfive lib) (libfive kernel) (libfive vec))

(define ffi_text (pointer->procedure '*
  (dynamic-func "text" stdlib)
  (list '* (list '* '*))))
(define* (text txt #:optional (pos #[0 0]))
  "text txt #:optional (pos #[0 0])
  "
  (ptr->shape (ffi_text
    (string->pointer txt)
    (vec2->tvec2 pos))))
(export text)
