#|
Guile bindings to the libfive CAD kernel

DO NOT EDIT BY HAND!
This file is automatically generated from libfive/stdlib/libfive_stdlib.h

It was last generated on 2022-02-09 19:39:26 by user bramp
|#

(define-module (libfive stdlib text))
(use-modules (system foreign) (libfive lib) (libfive kernel) (libfive vec))

(define ffi_text (pointer->procedure '*
  (dynamic-func "text" stdlib)
  (list '* (list '* '*))))
(define* (text txt #:optional (pos #[0 0]))
  "text txt #:optional (pos #[0 0])
  Returns the given text, rendered in a custom f-rep font
  (with a character height of 1)"
  (ptr->shape (ffi_text
    (string->pointer txt "latin1")
    (vec2->tvec2 pos))))
(export text)
