name: Linux-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install cmake pkg-config libeigen3-dev libpng-dev libboost-all-dev qtbase5-dev guile-2.2-dev tree

    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake ..
        make -j4

    - name: Test
      continue-on-error: true
      run: ./build/libfive/test/libfive-test

    - name: Tree
      run: tree ./build

    - uses: actions/upload-artifact@v2
      with:
        name: artifacts.zip
        path: |
          ./build/studio/Studio
          ./build/libfive/src/libfive.so
          ./build/libfive/bind/libfive-guile.so
