import os
from datetime import datetime

import parse
lib = parse.parse_stdlib()

header = '''#|
Guile bindings to the libfive CAD kernel

DO NOT EDIT BY HAND!
This file is automatically generated from libfive/stdlib/stdlib.h

It was last generated on {} by user {}
|#

(use-modules (libfive kernel))

(define stdlib (dynamic-link "libfive-stdlib"))
'''.format(datetime.now().strftime("%Y-%m-%d %H:%M:%S"), os.getlogin())

for module in ['csg']:
    for f in module.shapes:
        pass # TODO

